name: Update from UCSC

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pip3 install pandas tqdm numpy google dendropy
      - name: Download protobuf
        run: wget -q -N https://hgwdev.gi.ucsc.edu/~angie/UShER_SARS-CoV-2/public-latest.all.masked.pb
        working-directory: ./data_processing/
      - name: Download metadata
        run: wget  -q -N https://hgwdev.gi.ucsc.edu/~angie/UShER_SARS-CoV-2/public-latest.metadata.tsv.gz
        working-directory: ./data_processing/
      - name: Download accessions
        run: wget  -q -N https://github.com/CDCgov/SARS-CoV-2_Sequencing/raw/master/files/epiToPublic.tsv.gz
        working-directory: ./data_processing/
      - name: Download accessions
        run: wget  -q -N https://data.nextstrain.org/files/ncov/open/metadata.tsv.gz
        working-directory: ./data_processing/
      - name: Run
        run: python3 usher_processing.py
        working-directory: ./data_processing/
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
